language: node_js

node_js:
  - 8

cache:
  directories:
    - ~/.npm
    - node_modules

install:
  - yarn install && yarn run cypress:install

before_script:
  - yarn run start -- && sleep 1 &

script:
  - sleep 1 && yarn run cypress:run
