language: node_js

node_js:
  - 6

cache:
  directories:
    - ~/.npm
    - node_modules

before_install:
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn install && yarn run cypress:install

before_script:
  - greenkeeper-lockfile-update
  - yarn run ci:start -- &

script:
  - yarn run ci:test

after_script:
  - greenkeeper-lockfile-upload
